# Generated by Django 4.0.5 on 2022-08-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_employeeregister_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeregister',
            old_name='Employee_id',
            new_name='Employee_ID',
        ),
        migrations.RemoveField(
            model_name='employeeregister',
            name='username',
        ),
    ]
